### ISSUE TITLE
Containerized version of Citrahold

### ISSUE THREAD

**Issue by callephi** [regimensocial/Citrahold-3DS#4]
given that Citrahold relies on an outside server to backup data, is there a chance of instead using a Docker container? (especially given that the domain has expired rendering this service completely useless)

Would be mighty helpful as well for privacy as well as maintenance & cost

**Comment by regimensocial** [comment]
Hi, apologies for the late response.

I've been busy lately, thank you for telling me about the expired domain. Must've forgotten to tick autorenew, but I've just rebought the domain so that should be working again. Should be working in the morning because NameCheap/Verisign has maintenance, meaning I can't change anything at this time.

You can clone [Citrahold-Server](https://github.com/regimensocial/Citrahold-Server) and run it yourself. Change the config file on your 3DS to your own server address and you should be good as gold.

I've never used Docker before, but I will look into it.

Thank you

**Comment by callephi** [comment]
thank you for the quick response and renewing the domain so quickly!

i'm not personally familiar with docker on a developement level (i'm largely an end-user) but given the source code isn't too crazy i will actively look into seeing if i can develop a containerized version! even if no one else uses it, it's a nice learning experience for me haha

**Comment by callephi** [comment]
having a decent amount of issues getting Citrahold-Web up, after placing certs and building the server directory, index.ts won't build a runnable index.js, where I'm currently stuck with 
```
C:\Users\leader\Desktop\docker\citrahold-web-docker\index.js:315
                }, resolve, reject);
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\leader\Desktop\docker\citrahold-web-docker\node_modules\client-zip\index.js from C:\Users\leader\Desktop\docker\citrahold-web-docker\index.js not supported.
Instead change the require of C:\Users\leader\Desktop\docker\citrahold-web-docker\node_modules\client-zip\index.js in C:\Users\leader\Desktop\docker\citrahold-web-docker\index.js to a dynamic import() which is available in all CommonJS modules.
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (C:\Users\leader\Desktop\docker\citrahold-web-docker\index.js:40:20) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v22.11.0
```

unfortunately i'm not at all skilled in neither JS nor TS enough to make my way out of this, so at the moment i'm stuck even getting the front-end to run

**Comment by callephi** [comment]
scrap my last comment, installed older versions of `axios` and `client-zip` to help mediate this issue; however for whatever reason `citrahold.js` is not being parsed correctly and browser reports it gets lost at `citrahold.js:40:15` for `exports` not being defined (which even when it is by `let`, it then goes on to question `require` in context of `require("axios")` and `require ("client-zip")`

probably gonna leave it for tonight until the website is up to get an idea of how the frontend should be in action, hopefully i can get the frontend working to start on throwing a docker container together lol

**Comment by regimensocial** [comment]
Citrahold-Web is the weakest link of all four repositories; it's a nightmare. 

I made it in a really weird way because I didn't want to use React, and I did plan to eventually rewrite it in Svelte.

Later tomorrow, I'll look into it and hopefully produce some documentation for you on how to compile it. I think the version on my GitHub is somewhat outdated as I made a few changes when moving it to production.

**Comment by regimensocial** [comment]
Okay I've had a play about and figured out how I did it a year ago. Here's how to do it from scratch. This assumes you've already got Citrahold-Server working, if you're having trouble with that, let me know and I'll help.

1. `npm install --global serve` 
2. `git clone https://github.com/regimensocial/Citrahold-Web.git`
3. `cd Citrahold-Web`
4. `npm i`
5. `cd server`
6. `npm i`

7. edit `config.json` to change `serverAddress` to wherever you're hosting Citrahold-Server. The default might be okay but it depends however you're doing it.

It might just be easier to change it to be insecure, especially if this is just on your local network and you can trust everyone on it.

By default, the insecure port is 3000, so to do this, edit config.json to the following

```
{
    "serverAddress": "http://localhost:3000"
}
```

8. `cd ..`
9. `npm run buildAll`
10. `cd server/dist`
11. `serve . -p 3001` 

Running it on port 3001 means you won't have to edit anything in Citrahold-Server, as I've already allowed `http://localhost:3001` as an origin. You can change the origins in Citrahold-Server by going to the `config.json` there and adding to or modifying `allowedOrigins`.

Everything in server/dist is static and ready for hosting. 

This is done in an unusual way because `citrahold.js` is written in TypeScript and requires compilation first.

Please let me know how you get on. Please don't be afraid to ask for any more help.

**Comment by callephi** [comment]
thanks for the detailed instructions! Citrahold-Web now runs as (i presume) expected, however for whatever reason it will not recognize the server (running 3000/3443), i've changed `serverAddress` from `localhost:3000` to `localhost:3001` with no avail, but i fear it might be due to the selfsigned certs i'm using for Citrahold-Server which were made to get the thing running, as web console is returning `ERR_SSL_PROTOCOL_ERROR`

changing `securePort` to `0` as `src/index.js` implies would disable the need for SSL however still does not bypass this error, so honestly stumped here haha

**Comment by regimensocial** [comment]
Will look into this later

**Comment by regimensocial** [comment]
Your web browser will be upset about you using a self-signed certificate. On browsers like Chrome desktop, manually trusting it should do the trick.

If hosting it securely, and on the default port, go to `https://localhost:3443/". There will be a "Your connection is not private" type screen, and a button to **proceed anyway**. The button might be hidden behind some advanced option, but you need to click it. The site should then load. You'll see the default API page, but this isn't important.

Go back onto Citrahold Web on the same browser, and it should work fine.

Are you trying to specifically use a secured environment? Citrahold-3DS may have issues with the self-signed certificate... Let me know and I'll see what I can do for you. On local networks though, and for testing, I don't use HTTPS. I just have it be insecure.

**Comment by jarjarfinks** [comment]
I came to the repo to actually post this feature request. Also, is it possible to setup the Citrahold "PC" version as a docker container as well? It'd be nice to just have this running on my NAS and have it make files available for upload/download whenever I need it without having to run any desktop client to do so
